name: Deploy to Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Create .env file
      run: |
        cat << EOF > .env
        DOCKER_USER=${{ secrets.DOCKER_USER }}
        COMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}
        USER_ID=${{ secrets.USER_ID }}
        GROUP_ID=${{ secrets.GROUP_ID }}
        USERNAME=${{ secrets.USERNAME }}
        GROUPNAME=${{ secrets.GROUPNAME }}
        CLIENT_PORT=${{ secrets.CLIENT_PORT }}
        VITE_API_PORT=${{ secrets.VITE_API_PORT }}
        VITE_API_VERSION=${{ secrets.VITE_API_VERSION }}
        VITE_API_ADDRESS=$(hostname -I | awk '{print $1}')
        EOF
    
    - name: Build and push Docker image
      run: |
        # Step 1: Install dependencies and build app
        npm ci
        npm run build

        # Step 2: Build and push Docker image
        chmod +x setup-deployment.sh
        ./setup-deployment.sh

    - name: Install Docker on remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        script: |
            if ! command -v docker &> /dev/null; then
                curl -fsSL https://get.docker.com -o get-docker.sh
                sudo sh get-docker.sh
                sudo usermod -aG docker $USER
            fi
            if ! command -v docker-compose &> /dev/null; then
                sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi

    - name: Create and copy .env file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".env"
        target: "client/"

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".deployment/*"
        target: "client/"
        strip_components: 1

    - name: Install requirements on remote server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt update -y
            sudo apt upgrade -y
            sudo apt install docker-compose -y
            sudo apt install make -y

    - name: Execute remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd client
            sudo make clean
            sudo docker-compose pull
            sudo make setup